### ISSUE TITLE
BUG: Marks all changes on a page although only one Selected

### ISSUE THREAD

**Issue by crydotsnake** [Sebobo/Shel.Neos.WorkspaceModule#15]
If you have multiple changes on a page in a private workspace where a user is assigned, and you select a single change via the checkbox in the workspace review, he suddenly selects all other changes as well. The behavior should be that he only selects my selected change.

### Steps to reproduce
1. Make more changes on a page.
2. Review your workspace
3. Try to select only one change via the checkbox that has been published to a page.

### Expected Behavior
There should be only one change selected on the page

### Actual behavior
All my changes are selected by the checkbox.

**Comment by Sebobo** [comment]
Did you verify if this behaviour is different in the standard workspace module?

**Comment by crydotsnake** [comment]
> Did you verify if this behaviour is different in the standard workspace module?

I have checked it. In the standard Neos Workspace module the behavior is exactly the same.

**Comment by Sebobo** [comment]
Then this is not part of what I do right now in this package and the issue should be in Neos.Neos.

Keep in mind that it will automatically select all parent changes because the CR would run into an invalid state if those are not published too. Sibling changes should be ignored and not automatically checked.
