### ISSUE TITLE
Remove WorkspaceDetails entry from db when matching workspace is removed

### ISSUE THREAD

**Issue by Sebobo** [Sebobo/Shel.Neos.WorkspaceModule#3]

**Comment by so-grimm** [comment]
Hi,
I encountered a problem and I was wondering if this issue here actually means the same problem (hard to tell with no description). If not I'll open a new one.

The problem I'm facing:
When I try to delete a user, I get an error saying
```
An exception occurred while executing 'DELETE FROM neos_contentrepository_domain_model_workspace WHERE name = ?' with params ["user-redakteur"]

SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`<db-name>`.`shel_neos_workspacemodule_domain_model_workspacedetails`, CONSTRAINT `FK_923CCEA8D940019` FOREIGN KEY (`workspace`) REFERENCES `neos_contentrepository_domain_model_workspace` (`)
```

Is that what you encountered here too or a different problem entirely?

**Comment by Sebobo** [comment]
Hi @so-grimm, I'm not aware of that problem. This is actually resolved and I just tested it locally 🤔
Can you open a separate issue with more details like your Neos version, Plugin version, etc.
